/* SAÉ MS204
 * PARTIE 1
 * ARIDORY MALCOLM, VIDAL MARTIN
 * LOGIN : ARID0002
 */

-- 4 Chargement de la base INFO_EXPO

-- 4.a

-- TYPELIEU
INSERT INTO TYPELIEU VALUES (1, 'Musée municipal');
INSERT INTO TYPELIEU VALUES (2, 'Musée National');
INSERT INTO TYPELIEU VALUES (3, 'Musée Privé');
INSERT INTO TYPELIEU VALUES (4, 'Musée Départemental');
INSERT INTO TYPELIEU VALUES (5, 'Galerie d’art');
INSERT INTO TYPELIEU VALUES (6, 'Châteaux');
INSERT INTO TYPELIEU VALUES (7, 'Institutions culturelles');

-- DEPARTEMENT
INSERT INTO DEPARTEMENT VALUES (75, 'Paris');
INSERT INTO DEPARTEMENT VALUES (77, 'Seine-et-Marne');
INSERT INTO DEPARTEMENT VALUES (78, 'Yvelines');
INSERT INTO DEPARTEMENT VALUES (91, 'Essonne');
INSERT INTO DEPARTEMENT VALUES (92, 'Hauts-de-Seine');
INSERT INTO DEPARTEMENT VALUES (93, 'Seine-Saint-Denis');
INSERT INTO DEPARTEMENT VALUES (94, 'Val-de-Marne');
INSERT INTO DEPARTEMENT VALUES (95, 'Val-d’Oise');

-- GENRE
INSERT INTO GENRE VALUES (1, 'Architecture/Design/Mode');
INSERT INTO GENRE VALUES (2, 'Art Contemporain');
INSERT INTO GENRE VALUES (3, 'Beaux-Arts');
INSERT INTO GENRE VALUES (4, 'Châteaux/Monuments');
INSERT INTO GENRE VALUES (5, 'Galeries');
INSERT INTO GENRE VALUES (6, 'Histoire/Civilisations');
INSERT INTO GENRE VALUES (7, 'Instituts culturels');
INSERT INTO GENRE VALUES (8, 'Jeunes Publics');
INSERT INTO GENRE VALUES (9, 'Photographie');
INSERT INTO GENRE VALUES (10, 'Salons');
INSERT INTO GENRE VALUES (11, 'Sciences et Techniques');


